version: '3.3'
services: 
    mysql:
        image: mysql:8.0
        container_name: crocodile_mysql
        environment:
            MYSQL_ROOT_PASSWORD: "crocodile"
            MYSQL_DATABASE: "crocodile"
        volumes: 
          - "/zrtx/apt/mysqldata:/var/lib/mysql"   # mysql数据持久化
        restart: always
        ports: 
          - 13306:3306
    redis:
        image: redis:3.2.10
        container_name: crocodile_redis
        restart: always
        ports: 
          - 16379:6379