CREATE TABLE `os` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ip` CHAR(15) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`os` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`port` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`create_time` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `ip` (`ip`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
