ALTER TABLE `port_result` ADD COLUMN `task_id` CHAR(18) NOT NULL DEFAULT '' AFTER `run_task_id`;
ALTER TABLE `probe_result` ADD COLUMN `task_id` CHAR(18) NOT NULL DEFAULT '' AFTER `run_task_id`;
ALTER TABLE `plug_result` ADD COLUMN `task_id` CHAR(18) NOT NULL DEFAULT '' AFTER `run_task_id`;
ALTER TABLE `port_result`	ADD INDEX `task_id` (`task_id`);
ALTER TABLE `plug_result`	ADD INDEX `task_id` (`task_id`);
ALTER TABLE `probe_result`	ADD INDEX `task_id` (`task_id`);
UPDATE `probe_info` SET `probe_name`='特种木马-frp-http' WHERE  `probe_name`='frp-http';
UPDATE `probe_info` SET `probe_name`='SMB-fuso' WHERE  `probe_name`='fuso';
UPDATE `probe_info` SET `probe_name`='后门-gortcp' WHERE  `probe_name`='gortcp';
UPDATE `probe_info` SET `probe_name`='特种木马-gost' WHERE  `probe_name`='gost';
UPDATE `probe_info` SET `probe_name`='IPC管道-frp-tcp' WHERE  `probe_name`='frp-tcp';
UPDATE `probe_info` SET `probe_name`='后门-nps-http' WHERE  `probe_name`='nps-http';
UPDATE `probe_info` SET `probe_name`='特种木马-nps-backend' WHERE  `probe_name`='nps-backend';
