ALTER TABLE `task` ADD COLUMN `group` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '分组' AFTER `name`;
ALTER TABLE `os` ADD COLUMN `port` TEXT NULL AFTER `os`,ADD COLUMN `create_time` DATETIME NULL AFTER `port`;
